--FILE FORMATS (CRITICAL)
CREATE OR REPLACE FILE FORMAT BRONZE.CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STORAGE INTEGRATION NINJAS_EXT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::745247897940:role/DATA_NINJAS'
STORAGE_ALLOWED_LOCATIONS = ('s3://data-ninjas-s3/');

DESC INTEGRATION NINJAS_EXT;
--After this → configure IAM role in AWS

-- 4. EXTERNAL STAGE
CREATE OR REPLACE STAGE BRONZE.S3_STAGE
URL = 's3://data-ninjas-s3/raw_csv/'
STORAGE_INTEGRATION = NINJAS_EXT
FILE_FORMAT = CSV_FORMAT;

--5. BRONZE TABLES (RAW STRUCTURE)

-- CUSTOMERS
CREATE OR REPLACE TABLE BRONZE.CUSTOMERS_RAW (
    CUSTOMER_ID STRING,
    NAME STRING,
    CITY STRING,
    SIGNUP_DATE DATE,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

--PRODUCTS
CREATE OR REPLACE TABLE BRONZE.PRODUCTS_RAW (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

--ORDERS
CREATE OR REPLACE TABLE BRONZE.ORDERS_RAW (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

--ORDER_ITEMS
CREATE OR REPLACE TABLE BRONZE.ORDER_ITEMS_RAW (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY INT,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

--USER_ACTIVITY
CREATE OR REPLACE TABLE BRONZE.ACTIVITY_RAW (
    ACTIVITY_ID STRING,
    CUSTOMER_ID STRING,
    ACTIVITY_TYPE STRING,
    ACTIVITY_TIME TIMESTAMP,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

 --1. CUSTOMERS
COPY INTO NINJA_DB.BRONZE.CUSTOMERS_RAW
FROM (
    SELECT
        $1::STRING AS CUSTOMER_ID,
        $2::STRING AS NAME,
        $3::STRING AS CITY,
        TO_DATE($4) AS SIGNUP_DATE,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @NINJA_DB.BRONZE.S3_STAGE/customers/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

--2. PRODUCTS
COPY INTO BRONZE.PRODUCTS_RAW
FROM (
    SELECT
        $1::STRING AS PRODUCT_ID,
        $2::STRING AS PRODUCT_NAME,
        $3::STRING AS CATEGORY,
        $4::NUMBER AS PRICE,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @S3_STAGE/products/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

--3. ORDERS
COPY INTO BRONZE.ORDERS_RAW
FROM (
    SELECT
        $1::STRING AS ORDER_ID,
        $2::STRING AS CUSTOMER_ID,
        TO_DATE($3) AS ORDER_DATE,
        $4::NUMBER AS TOTAL_AMOUNT,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @S3_STAGE/orders/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

--4. ORDER_ITEMS
COPY INTO BRONZE.ORDER_ITEMS_RAW
FROM (
    SELECT
        $1::STRING AS ORDER_ITEM_ID,
        $2::STRING AS ORDER_ID,
        $3::STRING AS PRODUCT_ID,
        $4::NUMBER AS QUANTITY,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @S3_STAGE/order_items/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

--5. USER ACTIVITY
COPY INTO BRONZE.ACTIVITY_RAW
FROM (
    SELECT
        $1::STRING AS ACTIVITY_ID,
        $2::STRING AS CUSTOMER_ID,
        $3::STRING AS ACTIVITY_TYPE,
        TO_TIMESTAMP($4) AS ACTIVITY_TIME,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @S3_STAGE/activity/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

 --CREATE SNOWPIPES (AUTO INGEST)
 One pipe per table (best practice)

-- CUSTOMERS PIPE
CREATE OR REPLACE PIPE BRONZE.CUSTOMERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.CUSTOMERS_RAW
FROM (
    SELECT
        $1::STRING,
        $2::STRING,
        $3::STRING,
        TO_DATE($4),
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/customers/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--PRODUCTS PIPE
CREATE OR REPLACE PIPE BRONZE.PRODUCTS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.PRODUCTS_RAW
FROM (
    SELECT
        $1,$2,$3,$4,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/products/
    )
    FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--ORDERS PIPE
CREATE OR REPLACE PIPE BRONZE.ORDERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.ORDERS_RAW
FROM (
    SELECT
        $1,$2,TO_DATE($3),$4,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/orders/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--ORDER_ITEMS PIPE
CREATE OR REPLACE PIPE BRONZE.ORDER_ITEMS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.ORDER_ITEMS_RAW
FROM (
    SELECT
        $1,$2,$3,$4,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/order_items/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--ACTIVITY PIPE
CREATE OR REPLACE PIPE BRONZE.ACTIVITY_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.ACTIVITY_RAW
FROM (
    SELECT
        $1,$2,$3,TO_TIMESTAMP($4),
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/activity/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--to get notification channel
DESC PIPE NINJA_DB.BRONZE.CUSTOMERS_PIPE;

CREATE OR REPLACE STREAM BRONZE.CUSTOMERS_STREAM
ON TABLE BRONZE.CUSTOMERS_RAW;

CREATE OR REPLACE STREAM BRONZE.PRODUCTS_STREAM
ON TABLE BRONZE.PRODUCTS_RAW;

CREATE OR REPLACE STREAM BRONZE.ORDERS_STREAM
ON TABLE BRONZE.ORDERS_RAW;

CREATE OR REPLACE STREAM BRONZE.ORDER_ITEMS_STREAM
ON TABLE BRONZE.ORDER_ITEMS_RAW;

CREATE OR REPLACE STREAM BRONZE.ACTIVITY_STREAM
ON TABLE BRONZE.ACTIVITY_RAW;

DROP TABLE SILVER.ACTIVITY;