USE ROLE AUTOMATION_ROLE;
USE WAREHOUSE HACKATHON_WH;
USE DATABASE NINJA_DB;



USE SCHEMA BRONZE;

CREATE STREAM STR_CUSTOMERS
ON TABLE NINJA_DB.BRONZE.CUSTOMERS_RAW;

CREATE STREAM STR_PRODUCTS
ON TABLE NINJA_DB.BRONZE.PRODUCTS_RAW;

CREATE STREAM STR_ORDERS
ON TABLE NINJA_DB.BRONZE.ORDERS_RAW;

CREATE STREAM STR_ORDER_ITEMS
ON TABLE NINJA_DB.BRONZE.ORDER_ITEMS_RAW;

CREATE STREAM STR_USER_ACTIVITY
ON TABLE NINJA_DB.BRONZE.ACTIVITY_RAW;



CREATE OR REPLACE TASK AUTOMATION.TASK_ROOT
WAREHOUSE = HACKATHON_WH
SCHEDULE = '1 MINUTE'
AS
SELECT 1;



CREATE OR REPLACE TASK AUTOMATION.TASK_CUSTOMERS_SILVER
WAREHOUSE = HACKATHON_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.CUSTOMERS_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.CUSTOMERS tgt
USING (
SELECT
TRIM(customer_id) customer_id,
INITCAP(TRIM(name)) name,
INITCAP(TRIM(city)) city,
TO_DATE(signup_date) signup_date,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.CUSTOMERS_STREAM 
) src
ON tgt.customer_id = src.customer_id

WHEN MATCHED THEN UPDATE SET
name = src.name,
city = src.city,
signup_date = src.signup_date

WHEN NOT MATCHED THEN INSERT
(customer_id,name,city,signup_date,LOAD_TS)
VALUES
(src.customer_id,src.name,src.city,src.signup_date,src.LOAD_TS);



CREATE OR REPLACE TASK AUTOMATION.TASK_PRODUCTS_SILVER
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.PRODUCTS_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.PRODUCTS tgt
USING (
SELECT
TRIM(product_id) product_id,
INITCAP(TRIM(product_name)) product_name,
INITCAP(TRIM(category)) category,
TO_NUMBER(price) price,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.PRODUCTS_STREAM
) src
ON tgt.product_id = src.product_id

WHEN MATCHED THEN UPDATE SET
product_name = src.product_name,
category = src.category,
price = src.price

WHEN NOT MATCHED THEN INSERT
(product_id,product_name,category,price,LOAD_TS)
VALUES
(src.product_id,src.product_name,src.category,src.price,src.LOAD_TS);




CREATE OR REPLACE TASK AUTOMATION.TASK_ORDERS_SILVER
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.ORDERS_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.ORDERS tgt
USING (
SELECT
TRIM(order_id) order_id,
TRIM(customer_id) customer_id,
TO_DATE(order_date) order_date,
TO_NUMBER(total_amount) total_amount,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.ORDERS_STREAM
) src
ON tgt.order_id = src.order_id

WHEN MATCHED THEN UPDATE SET
customer_id = src.customer_id,
order_date = src.order_date,
total_amount = src.total_amount

WHEN NOT MATCHED THEN INSERT
(order_id,customer_id,order_date,total_amount,LOAD_TS)
VALUES
(src.order_id,src.customer_id,src.order_date,src.total_amount,src.LOAD_TS);



CREATE OR REPLACE TASK AUTOMATION.TASK_ORDER_ITEMS_SILVER
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.ORDER_ITEMS_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.ORDER_ITEMS tgt
USING (
SELECT
TRIM(order_item_id) order_item_id,
TRIM(order_id) order_id,
TRIM(product_id) product_id,
TO_NUMBER(quantity) quantity,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.ORDER_ITEMS_STREAM
) src
ON tgt.order_item_id = src.order_item_id

WHEN MATCHED THEN UPDATE SET
order_id = src.order_id,
product_id = src.product_id,
quantity = src.quantity

WHEN NOT MATCHED THEN INSERT
(order_item_id,order_id,product_id,quantity,LOAD_TS)
VALUES
(src.order_item_id,src.order_id,src.product_id,src.quantity,src.LOAD_TS);



CREATE OR REPLACE TASK AUTOMATION.TASK_ACTIVITY_SILVER
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.ACTIVITY_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.ACTIVITY tgt
USING (
SELECT
TRIM(activity_id) activity_id,
TRIM(customer_id) customer_id,
INITCAP(TRIM(activity_type)) activity_type,
TO_TIMESTAMP(activity_time) activity_time,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.ACTIVITY_STREAM
) src
ON tgt.activity_id = src.activity_id

WHEN MATCHED THEN UPDATE SET
customer_id = src.customer_id,
activity_type = src.activity_type,
activity_time = src.activity_time

WHEN NOT MATCHED THEN INSERT
(activity_id,customer_id,activity_type,activity_time,LOAD_TS)
VALUES
(src.activity_id,src.customer_id,src.activity_type,src.activity_time,src.LOAD_TS);



USE SCHEMA SILVER;

CREATE STREAM STR_SILVER_CUSTOMERS
ON TABLE NINJA_DB.SILVER.CUSTOMERS;

CREATE STREAM STR_SILVER_PRODUCTS
ON TABLE NINJA_DB.SILVER.PRODUCTS;

CREATE STREAM STR_SILVER_ORDERS
ON TABLE NINJA_DB.SILVER.ORDERS;

CREATE STREAM STR_SILVER_ORDER_ITEMS
ON TABLE NINJA_DB.SILVER.ORDER_ITEMS;

CREATE STREAM STR_SILVER_ACTIVITY
ON TABLE NINJA_DB.SILVER.ACTIVITY;



CREATE OR REPLACE TASK AUTOMATION.TASK_DIM_CUSTOMERS
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_CUSTOMERS_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.DIM_CUSTOMERS AS
SELECT customer_id,name,city,signup_date
FROM NINJA_DB.SILVER.CUSTOMERS;



CREATE OR REPLACE TASK AUTOMATION.TASK_DIM_PRODUCTS
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_PRODUCTS_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.DIM_PRODUCTS AS
SELECT product_id,product_name,category,price
FROM NINJA_DB.SILVER.PRODUCTS;



CREATE OR REPLACE TASK AUTOMATION.TASK_DIM_DATE
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ORDERS_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.DIM_DATE AS

WITH DATE_RANGE AS (
SELECT MIN(order_date) MIN_DATE,
MAX(order_date) MAX_DATE
FROM NINJA_DB.SILVER.ORDERS
),

DATE_SPINE AS (
SELECT DATEADD(DAY,SEQ4(),(SELECT MIN_DATE FROM DATE_RANGE)) DATE_KEY
FROM TABLE(GENERATOR(ROWCOUNT=>3650))
)

SELECT
DATE_KEY,
YEAR(DATE_KEY) YEAR,
QUARTER(DATE_KEY) QUARTER,
MONTH(DATE_KEY) MONTH,
MONTHNAME(DATE_KEY) MONTH_NAME,
WEEKOFYEAR(DATE_KEY) WEEK_OF_YEAR,
DAYOFMONTH(DATE_KEY) DAY_OF_MONTH
FROM DATE_SPINE
WHERE DATE_KEY <= (SELECT MAX_DATE FROM DATE_RANGE);



CREATE OR REPLACE TASK AUTOMATION.TASK_FACT_ORDER_ITEMS
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ORDER_ITEMS_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.FACT_ORDER_ITEMS AS
SELECT order_item_id,order_id,product_id,quantity
FROM NINJA_DB.SILVER.ORDER_ITEMS;



CREATE OR REPLACE TASK AUTOMATION.TASK_FACT_ORDERS
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_FACT_ORDER_ITEMS
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.FACT_ORDERS AS

SELECT
o.order_id,
o.customer_id,
oi.product_id,
oi.quantity,
o.total_amount,
o.order_date
FROM NINJA_DB.SILVER.ORDERS o
JOIN NINJA_DB.SILVER.ORDER_ITEMS oi
ON o.order_id = oi.order_id;



CREATE OR REPLACE TASK AUTOMATION.TASK_FACT_USER_ACTIVITY
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ACTIVITY_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.FACT_USER_ACTIVITY AS

SELECT
activity_id,
customer_id,
activity_type,
activity_time
FROM NINJA_DB.SILVER.USER_ACTIVITY;



ALTER TASK AUTOMATION.TASK_ROOT RESUME;

ALTER TASK AUTOMATION.TASK_CUSTOMERS_SILVER RESUME;
ALTER TASK AUTOMATION.TASK_PRODUCTS_SILVER RESUME;
ALTER TASK AUTOMATION.TASK_ORDERS_SILVER RESUME;
ALTER TASK AUTOMATION.TASK_ORDER_ITEMS_SILVER RESUME;
ALTER TASK AUTOMATION.TASK_ACTIVITY_SILVER RESUME;

ALTER TASK AUTOMATION.TASK_DIM_CUSTOMERS RESUME;
ALTER TASK AUTOMATION.TASK_DIM_PRODUCTS RESUME;
ALTER TASK AUTOMATION.TASK_DIM_DATE RESUME;
ALTER TASK AUTOMATION.TASK_FACT_ORDER_ITEMS RESUME;
ALTER TASK AUTOMATION.TASK_FACT_ORDERS RESUME;
ALTER TASK AUTOMATION.TASK_FACT_USER_ACTIVITY RESUME;