CREATE DATABASE NINJA_DB;
 
CREATE SCHEMA NINJA_DB.BRONZE;
CREATE SCHEMA NINJA_DB.SILVER;  
CREATE SCHEMA NINJA_DB.GOLD;
CREATE SCHEMA NINJA_DB.AUTOMATION;
CREATE SCHEMA NINJA_DB.ANALYTICS;

--🔹 Step 2 — Create Warehouse (Compute) 
CREATE WAREHOUSE HACKATHON_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

--FILE FORMATS (CRITICAL)
CREATE OR REPLACE FILE FORMAT BRONZE.CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STORAGE INTEGRATION NINJAS_EXT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::745247897940:role/DATA_NINJAS'
STORAGE_ALLOWED_LOCATIONS = ('s3://data-ninjas-s3/');

DESC INTEGRATION NINJAS_EXT;
--After this → configure IAM role in AWS

-- 4. EXTERNAL STAGE
CREATE OR REPLACE STAGE BRONZE.S3_STAGE
URL = 's3://data-ninjas-s3/raw_csv/'
STORAGE_INTEGRATION = NINJAS_EXT
FILE_FORMAT = CSV_FORMAT;

--5. BRONZE TABLES (RAW STRUCTURE)

-- CUSTOMERS
CREATE OR REPLACE TABLE BRONZE.CUSTOMERS_RAW (
    CUSTOMER_ID STRING,
    NAME STRING,
    CITY STRING,
    SIGNUP_DATE DATE,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

--PRODUCTS
CREATE OR REPLACE TABLE BRONZE.PRODUCTS_RAW (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

--ORDERS
CREATE OR REPLACE TABLE BRONZE.ORDERS_RAW (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

--ORDER_ITEMS
CREATE OR REPLACE TABLE BRONZE.ORDER_ITEMS_RAW (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY INT,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

SELECT * FROM BRONZE.PRODUCTS_RAW;
--USER_ACTIVITY
CREATE OR REPLACE TABLE BRONZE.ACTIVITY_RAW (
    ACTIVITY_ID STRING,
    CUSTOMER_ID STRING,
    ACTIVITY_TYPE STRING,
    ACTIVITY_TIME TIMESTAMP,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

 --1. CUSTOMERS
COPY INTO NINJA_DB.BRONZE.CUSTOMERS_RAW
FROM (
    SELECT
        $1::STRING AS CUSTOMER_ID,
        $2::STRING AS NAME,
        $3::STRING AS CITY,
        TO_DATE($4) AS SIGNUP_DATE,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @NINJA_DB.BRONZE.S3_STAGE/customers/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

--2. PRODUCTS
COPY INTO BRONZE.PRODUCTS_RAW
FROM (
    SELECT
        $1::STRING AS PRODUCT_ID,
        $2::STRING AS PRODUCT_NAME,
        $3::STRING AS CATEGORY,
        $4::NUMBER AS PRICE,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @S3_STAGE/products/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

--3. ORDERS
COPY INTO BRONZE.ORDERS_RAW
FROM (
    SELECT
        $1::STRING AS ORDER_ID,
        $2::STRING AS CUSTOMER_ID,
        TO_DATE($3) AS ORDER_DATE,
        $4::NUMBER AS TOTAL_AMOUNT,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @S3_STAGE/orders/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

--4. ORDER_ITEMS
COPY INTO BRONZE.ORDER_ITEMS_RAW
FROM (
    SELECT
        $1::STRING AS ORDER_ITEM_ID,
        $2::STRING AS ORDER_ID,
        $3::STRING AS PRODUCT_ID,
        $4::NUMBER AS QUANTITY,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @S3_STAGE/order_items/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

--5. USER ACTIVITY
COPY INTO BRONZE.ACTIVITY_RAW
FROM (
    SELECT
        $1::STRING AS ACTIVITY_ID,
        $2::STRING AS CUSTOMER_ID,
        $3::STRING AS ACTIVITY_TYPE,
        TO_TIMESTAMP($4) AS ACTIVITY_TIME,
        CURRENT_TIMESTAMP() AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @S3_STAGE/activity/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

 --CREATE SNOWPIPES (AUTO INGEST)
 One pipe per table (best practice)

-- CUSTOMERS PIPE
CREATE OR REPLACE PIPE BRONZE.CUSTOMERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.CUSTOMERS_RAW
FROM (
    SELECT
        $1::STRING,
        $2::STRING,
        $3::STRING,
        TO_DATE($4),
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/customers/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--PRODUCTS PIPE
CREATE OR REPLACE PIPE BRONZE.PRODUCTS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.PRODUCTS_RAW
FROM (
    SELECT
        $1,$2,$3,$4,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/products/
    )
    FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--ORDERS PIPE
CREATE OR REPLACE PIPE BRONZE.ORDERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.ORDERS_RAW
FROM (
    SELECT
        $1,$2,TO_DATE($3),$4,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/orders/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--ORDER_ITEMS PIPE
CREATE OR REPLACE PIPE BRONZE.ORDER_ITEMS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.ORDER_ITEMS_RAW
FROM (
    SELECT
        $1,$2,$3,$4,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/order_items/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--ACTIVITY PIPE
CREATE OR REPLACE PIPE BRONZE.ACTIVITY_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.ACTIVITY_RAW
FROM (
    SELECT
        $1,$2,$3,TO_TIMESTAMP($4),
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @NINJA_DB.BRONZE.S3_STAGE/activity/
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

--to get notification channel
DESC PIPE NINJA_DB.BRONZE.CUSTOMERS_PIPE;

CREATE OR REPLACE STREAM BRONZE.CUSTOMERS_STREAM
ON TABLE BRONZE.CUSTOMERS_RAW;

CREATE OR REPLACE STREAM BRONZE.PRODUCTS_STREAM
ON TABLE BRONZE.PRODUCTS_RAW;

CREATE OR REPLACE STREAM BRONZE.ORDERS_STREAM
ON TABLE BRONZE.ORDERS_RAW;

CREATE OR REPLACE STREAM BRONZE.ORDER_ITEMS_STREAM
ON TABLE BRONZE.ORDER_ITEMS_RAW;

CREATE OR REPLACE STREAM BRONZE.ACTIVITY_STREAM
ON TABLE BRONZE.ACTIVITY_RAW;

DROP TABLE SILVER.ACTIVITY;

CREATE SCHEMA IF NOT EXISTS SILVER;



--CLEANING

CREATE OR REPLACE TABLE SILVER.CUSTOMERS (
    CUSTOMER_ID STRING,
    NAME STRING,
    CITY STRING,
    SIGNUP_DATE DATE,
    LOAD_TS TIMESTAMP
);

CREATE OR REPLACE TABLE SILVER.PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER,
    LOAD_TS TIMESTAMP
);

CREATE OR REPLACE TABLE SILVER.ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER,
    LOAD_TS TIMESTAMP
);

CREATE OR REPLACE TABLE SILVER.ORDER_ITEMS (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY NUMBER,
    LOAD_TS TIMESTAMP
);

CREATE OR REPLACE TABLE SILVER.ACTIVITY (
    ACTIVITY_ID STRING,
    CUSTOMER_ID STRING,
    ACTIVITY_TYPE STRING,
    ACTIVITY_TIME TIMESTAMP,
    LOAD_TS TIMESTAMP
);
CREATE OR REPLACE STREAM BRONZE.CUSTOMERS_STREAM ON TABLE BRONZE.CUSTOMERS_RAW;
CREATE OR REPLACE STREAM BRONZE.PRODUCTS_STREAM ON TABLE BRONZE.PRODUCTS_RAW;
CREATE OR REPLACE STREAM BRONZE.ORDERS_STREAM ON TABLE BRONZE.ORDERS_RAW;
CREATE OR REPLACE STREAM BRONZE.ORDER_ITEMS_STREAM ON TABLE BRONZE.ORDER_ITEMS_RAW;
CREATE OR REPLACE STREAM BRONZE.ACTIVITY_STREAM ON TABLE BRONZE.ACTIVITY_RAW;






MERGE INTO SILVER.CUSTOMERS T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
            UPPER(TRIM(NAME)) AS NAME,
            UPPER(TRIM(CITY)) AS CITY,
            TRY_TO_DATE(SIGNUP_DATE) AS SIGNUP_DATE,
            LOAD_TS,

            ROW_NUMBER() OVER (
                PARTITION BY TRIM(CUSTOMER_ID)
                ORDER BY LOAD_TS DESC
            ) AS RN

        FROM BRONZE.CUSTOMERS_RAW

        WHERE CUSTOMER_ID IS NOT NULL
          AND TRIM(CUSTOMER_ID) != ''
    )
    WHERE RN = 1
      AND SIGNUP_DATE IS NOT NULL
      and name is not null
      and city is not null
) S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED THEN UPDATE SET
    NAME = S.NAME,
    CITY = S.CITY,
    SIGNUP_DATE = S.SIGNUP_DATE,
    LOAD_TS = S.LOAD_TS

WHEN NOT MATCHED THEN INSERT
VALUES (S.CUSTOMER_ID, S.NAME, S.CITY, S.SIGNUP_DATE, S.LOAD_TS);


MERGE INTO SILVER.PRODUCTS T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(PRODUCT_ID) AS PRODUCT_ID,
            UPPER(TRIM(PRODUCT_NAME)) AS PRODUCT_NAME,
            UPPER(TRIM(CATEGORY)) AS CATEGORY,
            COALESCE(PRICE, 0) AS PRICE,
            LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY TRIM(PRODUCT_ID)
                ORDER BY LOAD_TS DESC
            ) RN
        FROM BRONZE.PRODUCTS_RAW
        WHERE PRODUCT_ID IS NOT NULL
          AND TRIM(PRODUCT_ID) != ''
    and price is not null
    and category is not null
    and product_name is not null
    )
    WHERE RN = 1
) S
ON T.PRODUCT_ID = S.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
    PRODUCT_NAME = S.PRODUCT_NAME,
    CATEGORY = S.CATEGORY,
    PRICE = S.PRICE,
    LOAD_TS = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT
VALUES (S.PRODUCT_ID, S.PRODUCT_NAME, S.CATEGORY, S.PRICE, S.LOAD_TS);


MERGE INTO SILVER.ORDERS T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(ORDER_ID) AS ORDER_ID,
            TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
            TRY_TO_DATE(ORDER_DATE) AS ORDER_DATE,
            COALESCE(TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
            LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY TRIM(ORDER_ID)
                ORDER BY LOAD_TS DESC
            ) RN
        FROM BRONZE.ORDERS_RAW
        WHERE ORDER_ID IS NOT NULL
          AND CUSTOMER_ID IS NOT NULL
          and total_amount is not null
    )
    WHERE RN = 1
      AND ORDER_DATE IS NOT NULL
) S
ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED THEN UPDATE SET
    CUSTOMER_ID = S.CUSTOMER_ID,
    ORDER_DATE = S.ORDER_DATE,
    TOTAL_AMOUNT = S.TOTAL_AMOUNT,
    LOAD_TS = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT
VALUES (S.ORDER_ID, S.CUSTOMER_ID, S.ORDER_DATE, S.TOTAL_AMOUNT, S.LOAD_TS);


MERGE INTO SILVER.ORDER_ITEMS T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(ORDER_ITEM_ID) AS ORDER_ITEM_ID,
            TRIM(ORDER_ID) AS ORDER_ID,
            TRIM(PRODUCT_ID) AS PRODUCT_ID,
            COALESCE(QUANTITY, 1) AS QUANTITY,
            LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY TRIM(ORDER_ITEM_ID)
                ORDER BY LOAD_TS DESC
            ) RN
        FROM BRONZE.ORDER_ITEMS_RAW
        WHERE ORDER_ITEM_ID IS NOT NULL
          AND ORDER_ID IS NOT NULL
          AND PRODUCT_ID IS NOT NULL
          and quantity is not null
    )
    WHERE RN = 1
) S
ON T.ORDER_ITEM_ID = S.ORDER_ITEM_ID
WHEN MATCHED THEN UPDATE SET
    ORDER_ID = S.ORDER_ID,
    PRODUCT_ID = S.PRODUCT_ID,
    QUANTITY = S.QUANTITY,
    LOAD_TS = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT
VALUES (S.ORDER_ITEM_ID, S.ORDER_ID, S.PRODUCT_ID, S.QUANTITY, S.LOAD_TS);



MERGE INTO SILVER.ACTIVITY T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(ACTIVITY_ID) AS ACTIVITY_ID,
            TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
            UPPER(TRIM(ACTIVITY_TYPE)) AS ACTIVITY_TYPE,
            ACTIVITY_TIME,
            LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY TRIM(ACTIVITY_ID)
                ORDER BY LOAD_TS DESC
            ) RN
        FROM BRONZE.ACTIVITY_RAW
        WHERE ACTIVITY_ID IS NOT NULL
          AND CUSTOMER_ID IS NOT NULL
          and activity_time is not null
          and activity_type is not null
    )
    WHERE RN = 1
      AND ACTIVITY_TIME IS NOT NULL
) S
ON T.ACTIVITY_ID = S.ACTIVITY_ID
WHEN MATCHED THEN UPDATE SET
    CUSTOMER_ID = S.CUSTOMER_ID,
    ACTIVITY_TYPE = S.ACTIVITY_TYPE,
    ACTIVITY_TIME = S.ACTIVITY_TIME,
    LOAD_TS = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT
VALUES (S.ACTIVITY_ID, S.CUSTOMER_ID, S.ACTIVITY_TYPE, S.ACTIVITY_TIME, S.LOAD_TS);


SELECT * FROM NINJA_DB.SILVER.CUSTOMERS
SELECT * FROM NINJA_DB.SILVER.products
SELECT * FROM NINJA_DB.SILVER.activity
SELECT * FROM NINJA_DB.SILVER.order_items
SELECT * FROM NINJA_DB.SILVER.orders

USE DATABASE NINJA_DB;

create SCHEMA Duplicates;
USE schema duplicates;



CREATE OR REPLACE TABLE duplicates.CUSTOMERS_EXCEPTIONS AS
SELECT *
FROM BRONZE.CUSTOMERS_RAW
WHERE CUSTOMER_ID IS NULL
   OR TRIM(CUSTOMER_ID) = ''
   OR NAME IS NULL
   OR CITY IS NULL
   OR TRY_TO_DATE(SIGNUP_DATE) IS NULL;



CREATE OR REPLACE TABLE duplicates.PRODUCTS_EXCEPTIONS AS
SELECT *
FROM BRONZE.PRODUCTS_RAW
WHERE PRODUCT_ID IS NULL
   OR TRIM(PRODUCT_ID) = ''
   OR PRODUCT_NAME IS NULL
   OR CATEGORY IS NULL
   OR PRICE IS NULL;


CREATE OR REPLACE TABLE duplicates.ORDERS_EXCEPTIONS AS
SELECT *
FROM BRONZE.ORDERS_RAW
WHERE ORDER_ID IS NULL
   OR CUSTOMER_ID IS NULL
   OR TOTAL_AMOUNT IS NULL
   OR TRY_TO_DATE(ORDER_DATE) IS NULL;


CREATE OR REPLACE TABLE duplicates.ORDER_ITEMS_EXCEPTIONS AS
SELECT *
FROM BRONZE.ORDER_ITEMS_RAW
WHERE ORDER_ITEM_ID IS NULL
   OR ORDER_ID IS NULL
   OR PRODUCT_ID IS NULL
   OR QUANTITY IS NULL;


CREATE OR REPLACE TABLE duplicates.ACTIVITY_EXCEPTIONS AS
SELECT *
FROM BRONZE.ACTIVITY_RAW
WHERE ACTIVITY_ID IS NULL
   OR CUSTOMER_ID IS NULL
   OR ACTIVITY_TYPE IS NULL
   OR ACTIVITY_TIME IS NULL;


SELECT * FROM NINJA_DB.duplicates.CUSTOMERS_EXCEPTIONS;
SELECT * FROM NINJA_DB.duplicates.PRODUCTS_EXCEPTIONS;
SELECT * FROM NINJA_DB.duplicates.ORDERS_EXCEPTIONS;
SELECT * FROM NINJA_DB.duplicates.ORDER_ITEMS_EXCEPTIONS;
SELECT * FROM NINJA_DB.duplicates.ACTIVITY_EXCEPTIONS;


   SELECT * FROM NINJA_DB.gold.dim_CUSTOMERs;
      SELECT * FROM NINJA_DB.gold.dim_date;
         SELECT * FROM NINJA_DB.gold.dim_products;
            SELECT * FROM NINJA_DB.gold.fact_order_items;
               SELECT * FROM NINJA_DB.gold.fact_orders;
                  SELECT * FROM NINJA_DB.gold.fact_user_activity


    SELECT 
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM SILVER.CUSTOMERS C
JOIN SILVER.ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY 
    C.CUSTOMER_ID, C.NAME, C.CITY
ORDER BY TOTAL_SPENT DESC;


USE ROLE ACCOUNTADMIN_ROLE;
USE WAREHOUSE HACKATHON_WH;
USE DATABASE NINJA_DB;
USE SCHEMA GOLD;

-- STEP 1 — DIMENSION TABLES 


-- DIM_CUSTOMERS

ALTER TABLE GOLD.DIM_CUSTOMERS
DROP COLUMN valid_to;


CREATE OR REPLACE TABLE GOLD.DIM_CUSTOMERS (
    customer_sk INT AUTOINCREMENT,
    customer_id STRING,
    name STRING,
    city STRING,
    signup_date DATE,

    valid_from TIMESTAMP,
    is_active BOOLEAN,

    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

MERGE INTO GOLD.DIM_CUSTOMERS tgt
USING NINJA_DB.SILVER.CUSTOMERS src
ON tgt.customer_id = src.customer_id AND tgt.is_active = TRUE

WHEN MATCHED AND (
    tgt.name <> src.name OR
    tgt.city <> src.city
)
THEN UPDATE SET
    tgt.is_active = FALSE,
    tgt.updated_at = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT (
    customer_id, name, city, signup_date,
    valid_from, is_active, created_at, updated_at
)
VALUES (
    src.customer_id, src.name, src.city, src.signup_date,
    CURRENT_TIMESTAMP(), TRUE,
    CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- DIM_PRODUCTS
ALTER TABLE GOLD.DIM_PRODUCTS
DROP COLUMN valid_to;

CREATE OR REPLACE TABLE GOLD.DIM_PRODUCTS (
    product_sk INT AUTOINCREMENT,
    product_id STRING,
    product_name STRING,
    category STRING,
    price NUMBER,

    valid_from TIMESTAMP,
    is_active BOOLEAN,

    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

MERGE INTO GOLD.DIM_PRODUCTS tgt
USING NINJA_DB.SILVER.PRODUCTS src
ON tgt.product_id = src.product_id AND tgt.is_active = TRUE

WHEN MATCHED AND (
    tgt.product_name <> src.product_name OR
    tgt.category <> src.category OR
    tgt.price <> src.price
)
THEN UPDATE SET
    tgt.is_active = FALSE,
    tgt.updated_at = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT (
    product_id, product_name, category, price,
    valid_from, is_active, created_at, updated_at
)
VALUES (
    src.product_id, src.product_name, src.category, src.price,
    CURRENT_TIMESTAMP(), TRUE,
    CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);
-- STEP 2 — FACT TABLES

-- FACT_ORDERS
CREATE OR REPLACE TABLE GOLD.FACT_ORDERS (
    order_id STRING,
    customer_id STRING,
    order_date DATE,
    total_amount NUMBER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

MERGE INTO GOLD.FACT_ORDERS tgt
USING NINJA_DB.SILVER.ORDERS src
ON tgt.order_id = src.order_id

WHEN MATCHED THEN UPDATE SET
    tgt.customer_id = src.customer_id,
    tgt.order_date = src.order_date,
    tgt.total_amount = src.total_amount,
    tgt.updated_at = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT (
    order_id, customer_id, order_date,
    total_amount, created_at, updated_at
)
VALUES (
    src.order_id, src.customer_id, src.order_date,
    src.total_amount, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- FACT_ORDER_ITEMS


CREATE OR REPLACE TABLE GOLD.FACT_ORDER_ITEMS (
    order_item_id STRING,
    order_id STRING,
    product_id STRING,
    quantity NUMBER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

MERGE INTO GOLD.FACT_ORDER_ITEMS tgt
USING NINJA_DB.SILVER.ORDER_ITEMS src
ON tgt.order_item_id = src.order_item_id

WHEN MATCHED THEN UPDATE SET
    tgt.quantity = src.quantity,
    tgt.updated_at = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT (
    order_item_id,
    order_id,
    product_id,
    quantity,
    created_at,
    updated_at
)
VALUES (
    src.order_item_id,
    src.order_id,
    src.product_id,
    src.quantity,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);


-- FACT_USER_ACTIVITY
CREATE OR REPLACE TABLE GOLD.FACT_USER_ACTIVITY (
    activity_id STRING,
    customer_id STRING,
    activity_type STRING,
    activity_time TIMESTAMP,
    created_at TIMESTAMP
);

MERGE INTO GOLD.FACT_USER_ACTIVITY tgt
USING NINJA_DB.SILVER.ACTIVITY src
ON tgt.activity_id = src.activity_id

WHEN NOT MATCHED THEN
INSERT (
    activity_id, customer_id, activity_type,
    activity_time, created_at
)
VALUES (
    src.activity_id, src.customer_id, src.activity_type,
    src.activity_time, CURRENT_TIMESTAMP()
);


-- DIM_DATE (Common Date Dimension for all facts)
CREATE OR REPLACE TABLE GOLD.DIM_DATE AS
SELECT DISTINCT
    d.date_value AS date,

    EXTRACT(YEAR FROM d.date_value) AS year,
    EXTRACT(MONTH FROM d.date_value) AS month,
    EXTRACT(DAY FROM d.date_value) AS day,
    EXTRACT(DAYOFWEEK FROM d.date_value) AS day_of_week,
    EXTRACT(WEEK FROM d.date_value) AS week_of_year,
    EXTRACT(QUARTER FROM d.date_value) AS quarter,

    TO_VARCHAR(d.date_value, 'DY') AS day_name,
    TO_VARCHAR(d.date_value, 'MON') AS month_name,

    CASE 
        WHEN EXTRACT(DAYOFWEEK FROM d.date_value) IN (6,7) THEN 'WEEKEND'
        ELSE 'WEEKDAY'
    END AS day_type

FROM (
    SELECT order_date AS date_value FROM GOLD.FACT_ORDERS
    UNION
    SELECT DATE(activity_time) FROM GOLD.FACT_USER_ACTIVITY
) d;

USE ROLE AUTOMATION_ROLE;
USE WAREHOUSE HACKATHON_WH;
USE DATABASE NINJA_DB;



USE SCHEMA BRONZE;

CREATE STREAM STR_CUSTOMERS
ON TABLE NINJA_DB.BRONZE.CUSTOMERS_RAW;

CREATE STREAM STR_PRODUCTS
ON TABLE NINJA_DB.BRONZE.PRODUCTS_RAW;

CREATE STREAM STR_ORDERS
ON TABLE NINJA_DB.BRONZE.ORDERS_RAW;

CREATE STREAM STR_ORDER_ITEMS
ON TABLE NINJA_DB.BRONZE.ORDER_ITEMS_RAW;

CREATE STREAM STR_USER_ACTIVITY
ON TABLE NINJA_DB.BRONZE.ACTIVITY_RAW;



CREATE OR REPLACE TASK AUTOMATION.TASK_ROOT
WAREHOUSE = HACKATHON_WH
SCHEDULE = '1 MINUTE'
AS
SELECT 1;



CREATE OR REPLACE TASK AUTOMATION.TASK_CUSTOMERS_SILVER
WAREHOUSE = HACKATHON_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.CUSTOMERS_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.CUSTOMERS tgt
USING (
SELECT
TRIM(customer_id) customer_id,
INITCAP(TRIM(name)) name,
INITCAP(TRIM(city)) city,
TO_DATE(signup_date) signup_date,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.CUSTOMERS_STREAM 
) src
ON tgt.customer_id = src.customer_id

WHEN MATCHED THEN UPDATE SET
name = src.name,
city = src.city,
signup_date = src.signup_date

WHEN NOT MATCHED THEN INSERT
(customer_id,name,city,signup_date,LOAD_TS)
VALUES
(src.customer_id,src.name,src.city,src.signup_date,src.LOAD_TS);



CREATE OR REPLACE TASK AUTOMATION.TASK_PRODUCTS_SILVER
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.PRODUCTS_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.PRODUCTS tgt
USING (
SELECT
TRIM(product_id) product_id,
INITCAP(TRIM(product_name)) product_name,
INITCAP(TRIM(category)) category,
TO_NUMBER(price) price,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.PRODUCTS_STREAM
) src
ON tgt.product_id = src.product_id

WHEN MATCHED THEN UPDATE SET
product_name = src.product_name,
category = src.category,
price = src.price

WHEN NOT MATCHED THEN INSERT
(product_id,product_name,category,price,LOAD_TS)
VALUES
(src.product_id,src.product_name,src.category,src.price,src.LOAD_TS);




CREATE OR REPLACE TASK AUTOMATION.TASK_ORDERS_SILVER
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.ORDERS_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.ORDERS tgt
USING (
SELECT
TRIM(order_id) order_id,
TRIM(customer_id) customer_id,
TO_DATE(order_date) order_date,
TO_NUMBER(total_amount) total_amount,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.ORDERS_STREAM
) src
ON tgt.order_id = src.order_id

WHEN MATCHED THEN UPDATE SET
customer_id = src.customer_id,
order_date = src.order_date,
total_amount = src.total_amount

WHEN NOT MATCHED THEN INSERT
(order_id,customer_id,order_date,total_amount,LOAD_TS)
VALUES
(src.order_id,src.customer_id,src.order_date,src.total_amount,src.LOAD_TS);



CREATE OR REPLACE TASK AUTOMATION.TASK_ORDER_ITEMS_SILVER
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.ORDER_ITEMS_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.ORDER_ITEMS tgt
USING (
SELECT
TRIM(order_item_id) order_item_id,
TRIM(order_id) order_id,
TRIM(product_id) product_id,
TO_NUMBER(quantity) quantity,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.ORDER_ITEMS_STREAM
) src
ON tgt.order_item_id = src.order_item_id

WHEN MATCHED THEN UPDATE SET
order_id = src.order_id,
product_id = src.product_id,
quantity = src.quantity

WHEN NOT MATCHED THEN INSERT
(order_item_id,order_id,product_id,quantity,LOAD_TS)
VALUES
(src.order_item_id,src.order_id,src.product_id,src.quantity,src.LOAD_TS);



CREATE OR REPLACE TASK AUTOMATION.TASK_ACTIVITY_SILVER
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ROOT
WHEN SYSTEM$STREAM_HAS_DATA('NINJA_DB.BRONZE.ACTIVITY_STREAM')
AS

MERGE INTO NINJA_DB.SILVER.ACTIVITY tgt
USING (
SELECT
TRIM(activity_id) activity_id,
TRIM(customer_id) customer_id,
INITCAP(TRIM(activity_type)) activity_type,
TO_TIMESTAMP(activity_time) activity_time,
CURRENT_TIMESTAMP() LOAD_TS
FROM NINJA_DB.BRONZE.ACTIVITY_STREAM
) src
ON tgt.activity_id = src.activity_id

WHEN MATCHED THEN UPDATE SET
customer_id = src.customer_id,
activity_type = src.activity_type,
activity_time = src.activity_time

WHEN NOT MATCHED THEN INSERT
(activity_id,customer_id,activity_type,activity_time,LOAD_TS)
VALUES
(src.activity_id,src.customer_id,src.activity_type,src.activity_time,src.LOAD_TS);



USE SCHEMA SILVER;

CREATE STREAM STR_SILVER_CUSTOMERS
ON TABLE NINJA_DB.SILVER.CUSTOMERS;

CREATE STREAM STR_SILVER_PRODUCTS
ON TABLE NINJA_DB.SILVER.PRODUCTS;

CREATE STREAM STR_SILVER_ORDERS
ON TABLE NINJA_DB.SILVER.ORDERS;

CREATE STREAM STR_SILVER_ORDER_ITEMS
ON TABLE NINJA_DB.SILVER.ORDER_ITEMS;

CREATE STREAM STR_SILVER_ACTIVITY
ON TABLE NINJA_DB.SILVER.ACTIVITY;



CREATE OR REPLACE TASK AUTOMATION.TASK_DIM_CUSTOMERS
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_CUSTOMERS_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.DIM_CUSTOMERS AS
SELECT customer_id,name,city,signup_date
FROM NINJA_DB.SILVER.CUSTOMERS;



CREATE OR REPLACE TASK AUTOMATION.TASK_DIM_PRODUCTS
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_PRODUCTS_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.DIM_PRODUCTS AS
SELECT product_id,product_name,category,price
FROM NINJA_DB.SILVER.PRODUCTS;



CREATE OR REPLACE TASK AUTOMATION.TASK_DIM_DATE
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ORDERS_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.DIM_DATE AS

WITH DATE_RANGE AS (
SELECT MIN(order_date) MIN_DATE,
MAX(order_date) MAX_DATE
FROM NINJA_DB.SILVER.ORDERS
),

DATE_SPINE AS (
SELECT DATEADD(DAY,SEQ4(),(SELECT MIN_DATE FROM DATE_RANGE)) DATE_KEY
FROM TABLE(GENERATOR(ROWCOUNT=>3650))
)

SELECT
DATE_KEY,
YEAR(DATE_KEY) YEAR,
QUARTER(DATE_KEY) QUARTER,
MONTH(DATE_KEY) MONTH,
MONTHNAME(DATE_KEY) MONTH_NAME,
WEEKOFYEAR(DATE_KEY) WEEK_OF_YEAR,
DAYOFMONTH(DATE_KEY) DAY_OF_MONTH
FROM DATE_SPINE
WHERE DATE_KEY <= (SELECT MAX_DATE FROM DATE_RANGE);



CREATE OR REPLACE TASK AUTOMATION.TASK_FACT_ORDER_ITEMS
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ORDER_ITEMS_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.FACT_ORDER_ITEMS AS
SELECT order_item_id,order_id,product_id,quantity
FROM NINJA_DB.SILVER.ORDER_ITEMS;



CREATE OR REPLACE TASK AUTOMATION.TASK_FACT_ORDERS
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_FACT_ORDER_ITEMS
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.FACT_ORDERS AS

SELECT
o.order_id,
o.customer_id,
oi.product_id,
oi.quantity,
o.total_amount,
o.order_date
FROM NINJA_DB.SILVER.ORDERS o
JOIN NINJA_DB.SILVER.ORDER_ITEMS oi
ON o.order_id = oi.order_id;



CREATE OR REPLACE TASK AUTOMATION.TASK_FACT_USER_ACTIVITY
WAREHOUSE = TEAM_WH
AFTER AUTOMATION.TASK_ACTIVITY_SILVER
AS
CREATE OR REPLACE TABLE NINJA_DB.GOLD.FACT_USER_ACTIVITY AS

SELECT
activity_id,
customer_id,
activity_type,
activity_time
FROM NINJA_DB.SILVER.USER_ACTIVITY;



ALTER TASK AUTOMATION.TASK_ROOT RESUME;

ALTER TASK AUTOMATION.TASK_CUSTOMERS_SILVER RESUME;
ALTER TASK AUTOMATION.TASK_PRODUCTS_SILVER RESUME;
ALTER TASK AUTOMATION.TASK_ORDERS_SILVER RESUME;
ALTER TASK AUTOMATION.TASK_ORDER_ITEMS_SILVER RESUME;
ALTER TASK AUTOMATION.TASK_ACTIVITY_SILVER RESUME;

ALTER TASK AUTOMATION.TASK_DIM_CUSTOMERS RESUME;
ALTER TASK AUTOMATION.TASK_DIM_PRODUCTS RESUME;
ALTER TASK AUTOMATION.TASK_DIM_DATE RESUME;
ALTER TASK AUTOMATION.TASK_FACT_ORDER_ITEMS RESUME;
ALTER TASK AUTOMATION.TASK_FACT_ORDERS RESUME;
ALTER TASK AUTOMATION.TASK_FACT_USER_ACTIVITY RESUME;

--ANALYTICS
USE SCHEMA ANALYTICS;
-- 1. CUSTOMER 360
CREATE OR REPLACE TABLE ANALYTICS.CUSTOMER_360 AS
SELECT
    c.customer_id,
    c.name,
    c.city,
    c.signup_date,
    COUNT(DISTINCT o.order_id) AS total_orders,
    COALESCE(SUM(o.total_amount),0) AS total_spent,
    COALESCE(AVG(o.total_amount),0) AS avg_order_value,
    MAX(o.order_date) AS last_order_date
FROM GOLD.DIM_CUSTOMERS c
LEFT JOIN NINJA_DB.GOLD.FACT_ORDERS o
    ON c.customer_id = o.customer_id
WHERE c.is_active = TRUE
GROUP BY c.customer_id, c.name, c.city, c.signup_date;

-- 2. CUSTOMER SEGMENTATION (RFM)
CREATE OR REPLACE TABLE ANALYTICS.CUSTOMER_SEGMENTATION AS
SELECT
    customer_id,
    DATEDIFF('day', MAX(order_date), CURRENT_DATE()) AS recency,
    COUNT(order_id) AS frequency,
    SUM(total_amount) AS monetary,
    CASE
        WHEN SUM(total_amount) > 10000 THEN 'HIGH_VALUE'
        WHEN SUM(total_amount) BETWEEN 5000 AND 10000 THEN 'MEDIUM_VALUE'
        ELSE 'LOW_VALUE'
    END AS segment
FROM GOLD.FACT_ORDERS
GROUP BY customer_id;

-- 3. SALES INSIGHTS
CREATE OR REPLACE TABLE ANALYTICS.SALES_INSIGHTS AS
SELECT
    order_date,
    SUM(total_amount) AS revenue,
    COUNT(DISTINCT order_id) AS total_orders,
    SUM(total_amount) / COUNT(DISTINCT order_id) AS avg_order_value
FROM GOLD.FACT_ORDERS
GROUP BY order_date;

-- 4. CHURN IDENTIFICATION
CREATE OR REPLACE TABLE ANALYTICS.CUSTOMER_CHURN AS
SELECT
    customer_id,
    MAX(order_date) AS last_order_date,
    DATEDIFF('day', MAX(order_date), CURRENT_DATE()) AS days_inactive,
    CASE
        WHEN DATEDIFF('day', MAX(order_date), CURRENT_DATE()) > 90 THEN 'CHURNED'
        ELSE 'ACTIVE'
    END AS churn_status
FROM GOLD.FACT_ORDERS
GROUP BY customer_id;







--CUSTOMER 360 TASK
CREATE OR REPLACE TASK AUTOMATION.TASK_CUSTOMER_360
WAREHOUSE = HACKATHON_WH
AFTER AUTOMATION.TASK_FACT_ORDERS
AS

CREATE OR REPLACE TABLE GOLD.CUSTOMER_360 AS
SELECT
    c.customer_id,
    c.name,
    c.city,
    c.signup_date,
    COUNT(DISTINCT o.order_id) AS total_orders,
    COALESCE(SUM(o.total_amount),0) AS total_spent,
    COALESCE(AVG(o.total_amount),0) AS avg_order_value,
    MAX(o.order_date) AS last_order_date
FROM GOLD.DIM_CUSTOMERS c
LEFT JOIN GOLD.FACT_ORDERS o
    ON c.customer_id = o.customer_id
WHERE c.is_active = TRUE
GROUP BY c.customer_id, c.name, c.city, c.signup_date;



--CUSTOMER SEGMENTATION TASK
CREATE OR REPLACE TASK AUTOMATION.TASK_CUSTOMER_SEGMENT
WAREHOUSE = HACKATHON_WH
AFTER AUTOMATION.TASK_FACT_ORDERS
AS

CREATE OR REPLACE TABLE GOLD.CUSTOMER_SEGMENTATION AS
SELECT
    customer_id,
    DATEDIFF('day', MAX(order_date), CURRENT_DATE()) AS recency,
    COUNT(order_id) AS frequency,
    SUM(total_amount) AS monetary,
    CASE
        WHEN SUM(total_amount) > 10000 THEN 'HIGH_VALUE'
        WHEN SUM(total_amount) BETWEEN 5000 AND 10000 THEN 'MEDIUM_VALUE'
        ELSE 'LOW_VALUE'
    END AS segment
FROM GOLD.FACT_ORDERS
GROUP BY customer_id;



--3. SALES INSIGHTS TASK
CREATE OR REPLACE TASK AUTOMATION.TASK_SALES_INSIGHTS
WAREHOUSE = HACKATHON_WH
AFTER AUTOMATION.TASK_FACT_ORDERS
AS

CREATE OR REPLACE TABLE GOLD.SALES_INSIGHTS AS
SELECT
    d.date,
    d.month,
    d.year,
    SUM(f.total_amount) AS revenue,
    COUNT(DISTINCT f.order_id) AS total_orders,
    SUM(f.total_amount)/COUNT(DISTINCT f.order_id) AS avg_order_value
FROM GOLD.FACT_ORDERS f
JOIN GOLD.DIM_DATE d
    ON f.order_date = d.date
GROUP BY d.date, d.month, d.year;

SELECT * FROM ANALYTICS.SALES_INSIGHTS;
--CUSTOMER CHURN TASK
CREATE OR REPLACE TASK AUTOMATION.TASK_CUSTOMER_CHURN
WAREHOUSE = HACKATHON_WH
AFTER AUTOMATION.TASK_FACT_ORDERS
AS

CREATE OR REPLACE TABLE GOLD.CUSTOMER_CHURN AS
SELECT
    customer_id,
    MAX(order_date) AS last_order_date,
    DATEDIFF('day', MAX(order_date), CURRENT_DATE()) AS days_inactive,
    CASE
        WHEN DATEDIFF('day', MAX(order_date), CURRENT_DATE()) > 90 THEN 'CHURNED'
        ELSE 'ACTIVE'
    END AS churn_status
FROM GOLD.FACT_ORDERS
GROUP BY customer_id;

SELECT * FROM ANALYTICS.CUSTOMER_CHURN;
