/*How Team Works in ONE Account (Clear Picture)
Think like this:

1 Snowflake Account
   ↓
1 Database (RETAIL_DB)
   ↓
3 Layers → BRONZE | SILVER | GOLD
   ↓
5 Users (each with different roles)
👉 Same system, but controlled access
*/
--👥 Step-by-Step Setup (Do This Once)
--🔹 Step 1 — Create Database & Layers

CREATE DATABASE NINJA_DB;
 
CREATE SCHEMA NINJA_DB.BRONZE;
CREATE SCHEMA NINJA_DB.SILVER;  
CREATE SCHEMA NINJA_DB.GOLD;
CREATE SCHEMA NINJA_DB.AUTOMATION;
CREATE SCHEMA NINJA_DB.ANALYTICS;

--🔹 Step 2 — Create Warehouse (Compute) 
CREATE WAREHOUSE HACKATHON_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

--👤 Step 3 — Create Roles (Divide Work)
--Each role = one team responsibility

CREATE ROLE INGESTION_ROLE;
CREATE ROLE CLEANING_ROLE;
CREATE ROLE TRANSFORM_ROLE;
CREATE ROLE AUTOMATION_ROLE;
CREATE ROLE ANALYTICS_ROLE;

--👥 Step 4 — Create Users
--Each teammate gets a login

CREATE USER surya2 PASSWORD='123';
CREATE USER jagadeesh PASSWORD='123';
CREATE USER kalyan PASSWORD='123';
CREATE USER charith PASSWORD='123';
CREATE USER srinivas PASSWORD='123';

--🔗 Step 5 — Assign Roles to Users
GRANT ROLE ACCOUNTADMIN TO USER surya2;
GRANT ROLE ACCOUNTADMIN TO USER jagadeesh;
GRANT ROLE ACCOUNTADMIN TO USER kalyan;
GRANT ROLE ACCOUNTADMIN TO USER charith;
GRANT ROLE ACCOUNTADMIN TO USER srinivas;




--🔐 Step 6 — Give Access (VERY IMPORTANT)
--👉 Ingestion person (Bronze)
GRANT USAGE ON DATABASE NINJA_DB TO ROLE INGESTION_ROLE;
GRANT USAGE ON SCHEMA NINJA_DB.BRONZE TO ROLE INGESTION_ROLE;

GRANT CREATE TABLE ON SCHEMA NINJA_DB.BRONZE TO ROLE INGESTION_ROLE;

GRANT USAGE ON WAREHOUSE HACKATHON_WH TO ROLE INGESTION_ROLE;

-- Allow ingestion role to create file formats
GRANT CREATE FILE FORMAT ON SCHEMA NINJA_DB.BRONZE TO ROLE INGESTION_ROLE;

-- Allow ingestion role to create stage
GRANT CREATE STAGE ON SCHEMA NINJA_DB.BRONZE TO ROLE INGESTION_ROLE;
--grant all privilages
GRANT ALL PRIVILEGES ON SCHEMA NINJA_DB.BRONZE TO ROLE INGESTION_ROLE;
--INTEGRATION
GRANT USAGE ON INTEGRATION NINJAS_EXT TO ROLE INGESTION_ROLE;


--👉 Cleaning person (Silver)
GRANT USAGE ON DATABASE NINJA_DB TO ROLE CLEANING_ROLE;
GRANT USAGE ON SCHEMA NINJA_DB.SILVER TO ROLE CLEANING_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA NINJA_DB.BRONZE TO ROLE CLEANING_ROLE;
GRANT CREATE TABLE ON SCHEMA NINJA_DB.SILVER TO ROLE CLEANING_ROLE;
-- Allow cleaning role to read bronze
GRANT USAGE ON SCHEMA NINJA_DB.BRONZE TO ROLE CLEANING_ROLE;

-- Future-proof (very important)
GRANT SELECT ON FUTURE TABLES IN SCHEMA NINJA_DB.BRONZE TO ROLE CLEANING_ROLE;
GRANT USAGE ON WAREHOUSE HACKATHON_WH TO ROLE CLEANING_ROLE;
--grant all privilages
GRANT ALL PRIVILEGES ON SCHEMA NINJA_DB.SILVER TO ROLE CLEANING_ROLE;

--👉 Transformation person (Gold)
GRANT USAGE ON DATABASE NINJA_DB TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA NINJA_DB.GOLD TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA NINJA_DB.SILVER TO ROLE TRANSFORM_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA NINJA_DB.SILVER TO ROLE TRANSFORM_ROLE;
GRANT CREATE TABLE ON SCHEMA NINJA_DB.GOLD TO ROLE TRANSFORM_ROLE;
GRANT CREATE TABLE ON SCHEMA NINJA_DB.SILVER TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE HACKATHON_WH TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NINJA_DB.SILVER TO ROLE TRANSFORM_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA NINJA_DB.GOLD TO ROLE TRANSFORM_ROLE;

--👉 Analytics person (Read-only)
GRANT USAGE ON DATABASE NINJA_DB TO ROLE ANALYTICS_ROLE;
GRANT USAGE ON SCHEMA NINJA_DB.GOLD TO ROLE ANALYTICS_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA NINJA_DB.GOLD TO ROLE ANALYTICS_ROLE;

GRANT USAGE ON WAREHOUSE TEAM_WH TO ROLE ANALYTICS_ROLE;

--Automation
GRANT USAGE ON DATABASE RETAIL2_DB TO ROLE AUTOMATION_ROLE;

GRANT USAGE ON SCHEMA NINJA_DB.BRONZE TO ROLE AUTOMATION_ROLE;
GRANT USAGE ON SCHEMA NINJA_DB.SILVER TO ROLE AUTOMATION_ROLE;
GRANT USAGE ON SCHEMA NINJA_DB.GOLD TO ROLE AUTOMATION_ROLE;
GRANT USAGE ON SCHEMA NINJA_DB.AUTOMATION TO ROLE AUTOMATION_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA NINJA_DB.SILVER TO ROLE AUTOMATION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA NINJA_DB.GOLD TO ROLE AUTOMATION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA NINJA_DB.BRONZE TO ROLE AUTOMATION_ROLE;
GRANT USAGE ON WAREHOUSE HACKATHON_WH TO ROLE AUTOMATION_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA NINJA_DB.GOLD TO ROLE AUTOMATION_ROLE;

-- Stream creation permission
GRANT CREATE STREAM ON SCHEMA NINJA_DB.BRONZE TO ROLE AUTOMATION_ROLE;
GRANT CREATE STREAM ON SCHEMA NINJA_DB.SILVER TO ROLE AUTOMATION_ROLE;
-- Allow creating tasks
GRANT CREATE TASK ON SCHEMA NINJA_DB.BRONZE TO ROLE AUTOMATION_ROLE;
GRANT CREATE TASK ON SCHEMA NINJA_DB.SILVER TO ROLE AUTOMATION_ROLE;
GRANT CREATE TASK ON SCHEMA NINJA_DB.GOLD TO ROLE AUTOMATION_ROLE;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE AUTOMATION_ROLE;

GRANT USAGE ON DATABASE NINJA_DB TO ROLE AUTOMATION_ROLE;

GRANT USAGE ON SCHEMA NINJA_DB.BRONZE TO ROLE AUTOMATION_ROLE;
--PIPES
GRANT CREATE PIPE ON SCHEMA NINJA_DB.BRONZE TO ROLE AUTOMATION_ROLE;

GRANT USAGE ON INTEGRATION NINJAS_EXT TO ROLE AUTOMATION_ROLE;

--🔄 Step 7 — How Each Member Works
--Each teammate logs in and sets their role:

USE ROLE INGESTION_ROLE;
USE WAREHOUSE TEAM_WH;
USE DATABASE RETAIL2_DB;
USE SCHEMA BRONZE;

SHOW
--Others will use their own roles and schemas.
/*
⚡ Real Hackathon Flow (Super Clear)
👤 Member 1 (Ingestion)
Upload files

Run COPY INTO

Create BRONZE tables

👤 Member 2 (Cleaning)
Read from BRONZE

Clean data

Create SILVER tables

👤 Member 3 (Transformation)
Read from SILVER

Create FACT & DIM tables in GOLD

👤 Member 4 (Automation)
Create STREAMS & TASKS

👤 Member 5 (Analytics)
Write queries

Build dashboard
*/

GRANT USAGE ON DATABASE RETAIL2_DB TO ROLE INGESTION_ROLE;
GRANT USAGE ON DATABASE RETAIL2_DB TO ROLE CLEANING_ROLE;
GRANT USAGE ON DATABASE RETAIL2_DB TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON DATABASE RETAIL2_DB TO ROLE AUTOMATION_ROLE;
GRANT USAGE ON DATABASE RETAIL2_DB TO ROLE ANALYTICS_ROLE;



 --3. STORAGE INTEGRATION (S3 EXAMPLE)
-- Run as SYSADMIN

CREATE OR REPLACE STORAGE INTEGRATION NINJAS_EXT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::745247897940:role/DATA_NINJAS'
STORAGE_ALLOWED_LOCATIONS = ('s3://data-ninjas-s3/');

--Get IAM details
DESC INTEGRATION NINJAS_EXT;




