CREATE SCHEMA IF NOT EXISTS SILVER;


CREATE OR REPLACE TABLE SILVER.CUSTOMERS (
    CUSTOMER_ID STRING,
    NAME STRING,
    CITY STRING,
    SIGNUP_DATE DATE,
    LOAD_TS TIMESTAMP
);

CREATE OR REPLACE TABLE SILVER.PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER,
    LOAD_TS TIMESTAMP
);

CREATE OR REPLACE TABLE SILVER.ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER,
    LOAD_TS TIMESTAMP
);

CREATE OR REPLACE TABLE SILVER.ORDER_ITEMS (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY NUMBER,
    LOAD_TS TIMESTAMP
);

CREATE OR REPLACE TABLE SILVER.ACTIVITY (
    ACTIVITY_ID STRING,
    CUSTOMER_ID STRING,
    ACTIVITY_TYPE STRING,
    ACTIVITY_TIME TIMESTAMP,
    LOAD_TS TIMESTAMP
);
CREATE OR REPLACE STREAM BRONZE.CUSTOMERS_STREAM ON TABLE BRONZE.CUSTOMERS_RAW;
CREATE OR REPLACE STREAM BRONZE.PRODUCTS_STREAM ON TABLE BRONZE.PRODUCTS_RAW;
CREATE OR REPLACE STREAM BRONZE.ORDERS_STREAM ON TABLE BRONZE.ORDERS_RAW;
CREATE OR REPLACE STREAM BRONZE.ORDER_ITEMS_STREAM ON TABLE BRONZE.ORDER_ITEMS_RAW;
CREATE OR REPLACE STREAM BRONZE.ACTIVITY_STREAM ON TABLE BRONZE.ACTIVITY_RAW;


👉 This is the core logic




MERGE INTO SILVER.CUSTOMERS T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
            UPPER(TRIM(NAME)) AS NAME,
            UPPER(TRIM(CITY)) AS CITY,
            TRY_TO_DATE(SIGNUP_DATE) AS SIGNUP_DATE,
            LOAD_TS,

            ROW_NUMBER() OVER (
                PARTITION BY TRIM(CUSTOMER_ID)
                ORDER BY LOAD_TS DESC
            ) AS RN

        FROM BRONZE.CUSTOMERS_RAW

        WHERE CUSTOMER_ID IS NOT NULL
          AND TRIM(CUSTOMER_ID) != ''
    )
    WHERE RN = 1
      AND SIGNUP_DATE IS NOT NULL
      and name is not null
      and city is not null
) S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED THEN UPDATE SET
    NAME = S.NAME,
    CITY = S.CITY,
    SIGNUP_DATE = S.SIGNUP_DATE,
    LOAD_TS = S.LOAD_TS

WHEN NOT MATCHED THEN INSERT
VALUES (S.CUSTOMER_ID, S.NAME, S.CITY, S.SIGNUP_DATE, S.LOAD_TS);


MERGE INTO SILVER.PRODUCTS T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(PRODUCT_ID) AS PRODUCT_ID,
            UPPER(TRIM(PRODUCT_NAME)) AS PRODUCT_NAME,
            UPPER(TRIM(CATEGORY)) AS CATEGORY,
            COALESCE(PRICE, 0) AS PRICE,
            LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY TRIM(PRODUCT_ID)
                ORDER BY LOAD_TS DESC
            ) RN
        FROM BRONZE.PRODUCTS_RAW
        WHERE PRODUCT_ID IS NOT NULL
          AND TRIM(PRODUCT_ID) != ''
    and price is not null
    and category is not null
    and product_name is not null
    )
    WHERE RN = 1
) S
ON T.PRODUCT_ID = S.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
    PRODUCT_NAME = S.PRODUCT_NAME,
    CATEGORY = S.CATEGORY,
    PRICE = S.PRICE,
    LOAD_TS = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT
VALUES (S.PRODUCT_ID, S.PRODUCT_NAME, S.CATEGORY, S.PRICE, S.LOAD_TS);


MERGE INTO SILVER.ORDERS T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(ORDER_ID) AS ORDER_ID,
            TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
            TRY_TO_DATE(ORDER_DATE) AS ORDER_DATE,
            COALESCE(TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
            LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY TRIM(ORDER_ID)
                ORDER BY LOAD_TS DESC
            ) RN
        FROM BRONZE.ORDERS_RAW
        WHERE ORDER_ID IS NOT NULL
          AND CUSTOMER_ID IS NOT NULL
          and total_amount is not null
    )
    WHERE RN = 1
      AND ORDER_DATE IS NOT NULL
) S
ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED THEN UPDATE SET
    CUSTOMER_ID = S.CUSTOMER_ID,
    ORDER_DATE = S.ORDER_DATE,
    TOTAL_AMOUNT = S.TOTAL_AMOUNT,
    LOAD_TS = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT
VALUES (S.ORDER_ID, S.CUSTOMER_ID, S.ORDER_DATE, S.TOTAL_AMOUNT, S.LOAD_TS);


MERGE INTO SILVER.ORDER_ITEMS T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(ORDER_ITEM_ID) AS ORDER_ITEM_ID,
            TRIM(ORDER_ID) AS ORDER_ID,
            TRIM(PRODUCT_ID) AS PRODUCT_ID,
            COALESCE(QUANTITY, 1) AS QUANTITY,
            LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY TRIM(ORDER_ITEM_ID)
                ORDER BY LOAD_TS DESC
            ) RN
        FROM BRONZE.ORDER_ITEMS_RAW
        WHERE ORDER_ITEM_ID IS NOT NULL
          AND ORDER_ID IS NOT NULL
          AND PRODUCT_ID IS NOT NULL
          and quantity is not null
    )
    WHERE RN = 1
) S
ON T.ORDER_ITEM_ID = S.ORDER_ITEM_ID
WHEN MATCHED THEN UPDATE SET
    ORDER_ID = S.ORDER_ID,
    PRODUCT_ID = S.PRODUCT_ID,
    QUANTITY = S.QUANTITY,
    LOAD_TS = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT
VALUES (S.ORDER_ITEM_ID, S.ORDER_ID, S.PRODUCT_ID, S.QUANTITY, S.LOAD_TS);



MERGE INTO SILVER.ACTIVITY T
USING (
    SELECT *
    FROM (
        SELECT
            TRIM(ACTIVITY_ID) AS ACTIVITY_ID,
            TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
            UPPER(TRIM(ACTIVITY_TYPE)) AS ACTIVITY_TYPE,
            ACTIVITY_TIME,
            LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY TRIM(ACTIVITY_ID)
                ORDER BY LOAD_TS DESC
            ) RN
        FROM BRONZE.ACTIVITY_RAW
        WHERE ACTIVITY_ID IS NOT NULL
          AND CUSTOMER_ID IS NOT NULL
          and activity_time is not null
          and activity_type is not null
    )
    WHERE RN = 1
      AND ACTIVITY_TIME IS NOT NULL
) S
ON T.ACTIVITY_ID = S.ACTIVITY_ID
WHEN MATCHED THEN UPDATE SET
    CUSTOMER_ID = S.CUSTOMER_ID,
    ACTIVITY_TYPE = S.ACTIVITY_TYPE,
    ACTIVITY_TIME = S.ACTIVITY_TIME,
    LOAD_TS = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT
VALUES (S.ACTIVITY_ID, S.CUSTOMER_ID, S.ACTIVITY_TYPE, S.ACTIVITY_TIME, S.LOAD_TS);


SELECT * FROM NINJA_DB.SILVER.CUSTOMERS
SELECT * FROM NINJA_DB.SILVER.products
SELECT * FROM NINJA_DB.SILVER.activity
SELECT * FROM NINJA_DB.SILVER.order_items
SELECT * FROM NINJA_DB.SILVER.orders

USE DATABASE NINJA_DB;

create SCHEMA Duplicates;
USE schema duplicates;



CREATE OR REPLACE TABLE duplicates.CUSTOMERS_EXCEPTIONS AS
SELECT *
FROM BRONZE.CUSTOMERS_RAW
WHERE CUSTOMER_ID IS NULL
   OR TRIM(CUSTOMER_ID) = ''
   OR NAME IS NULL
   OR CITY IS NULL
   OR TRY_TO_DATE(SIGNUP_DATE) IS NULL;



CREATE OR REPLACE TABLE duplicates.PRODUCTS_EXCEPTIONS AS
SELECT *
FROM BRONZE.PRODUCTS_RAW
WHERE PRODUCT_ID IS NULL
   OR TRIM(PRODUCT_ID) = ''
   OR PRODUCT_NAME IS NULL
   OR CATEGORY IS NULL
   OR PRICE IS NULL;


CREATE OR REPLACE TABLE duplicates.ORDERS_EXCEPTIONS AS
SELECT *
FROM BRONZE.ORDERS_RAW
WHERE ORDER_ID IS NULL
   OR CUSTOMER_ID IS NULL
   OR TOTAL_AMOUNT IS NULL
   OR TRY_TO_DATE(ORDER_DATE) IS NULL;


CREATE OR REPLACE TABLE duplicates.ORDER_ITEMS_EXCEPTIONS AS
SELECT *
FROM BRONZE.ORDER_ITEMS_RAW
WHERE ORDER_ITEM_ID IS NULL
   OR ORDER_ID IS NULL
   OR PRODUCT_ID IS NULL
   OR QUANTITY IS NULL;


CREATE OR REPLACE TABLE duplicates.ACTIVITY_EXCEPTIONS AS
SELECT *
FROM BRONZE.ACTIVITY_RAW
WHERE ACTIVITY_ID IS NULL
   OR CUSTOMER_ID IS NULL
   OR ACTIVITY_TYPE IS NULL
   OR ACTIVITY_TIME IS NULL;


SELECT * FROM NINJA_DB.duplicates.CUSTOMERS_EXCEPTIONS;
SELECT * FROM NINJA_DB.duplicates.PRODUCTS_EXCEPTIONS;
SELECT * FROM NINJA_DB.duplicates.ORDERS_EXCEPTIONS;
SELECT * FROM NINJA_DB.duplicates.ORDER_ITEMS_EXCEPTIONS;
SELECT * FROM NINJA_DB.duplicates.ACTIVITY_EXCEPTIONS;


   SELECT * FROM NINJA_DB.gold.dim_CUSTOMERs;
      SELECT * FROM NINJA_DB.gold.dim_date;
         SELECT * FROM NINJA_DB.gold.dim_products;
            SELECT * FROM NINJA_DB.gold.fact_order_items;
               SELECT * FROM NINJA_DB.gold.fact_orders;
                  SELECT * FROM NINJA_DB.gold.fact_user_activity


    SELECT 
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM SILVER.CUSTOMERS C
JOIN SILVER.ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY 
    C.CUSTOMER_ID, C.NAME, C.CITY
ORDER BY TOTAL_SPENT DESC;